version: "3"

services:
    redis:
        image: redis
        expose: 
            - "6379"
        container_name: redis

    flask-app:
        image: kiranpesarlanka/tweeny:v1
        ports:
            - "9090:9090"
        depends_on:
            - redis
